<%@ Page Title="About" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="About.aspx.vb" Inherits="About" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        
    </hgroup>
    <div class="tit-news-main" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 24px; line-height: 36px; font-family: Arial, Helvetica, sans-serif; color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        Giới thiệu Công ty</div>
    <div class="time-post" style="box-sizing: border-box; margin: 5px 0px; padding: 0px; border: 0px none; font-style: italic; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 12px; line-height: inherit; font-family: Arial, Helvetica, sans-serif; color: rgb(153, 153, 153); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        17:28 07/10/2008</div>
    <div class="news-content" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-weight: normal; font-stretch: inherit; font-size: 12px; line-height: 21.6px; font-family: Arial, Helvetica, sans-serif; color: rgb(51, 51, 51); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <p class="MsoNormal" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; text-align: justify;">
        </p>
        <p class="MsoNormal" style="box-sizing: border-box; margin: 0in 0in 0.0001pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; text-indent: -0.25in;">
        </p>
        <p class="MsoNormal" style="box-sizing: border-box; margin: 0in 0in 0.0001pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; text-indent: -0.25in; text-align: justify;">
        </p>
        <p class="MsoNormal" style="box-sizing: border-box; margin: 0in 0in 0.0001pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20.4px; font-family: inherit; text-indent: -0.25in;">
            &nbsp;</p>
        <p class="MsoNormal" style="box-sizing: border-box; margin: 6pt 0in 6pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-indent: -0.25in;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: tahoma;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">Tên Công ty:<strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">&nbsp;CÔNG TY CỔ PHẦN THẾ GIỚI SỐ TRẦN ANH</strong><o:p style="box-sizing: border-box; margin: 0px; padding: 0px;"></o:p></span></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in 6pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-indent: -0.25in;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Tên giao dịch tiếng Anh:<strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>TRANANH DIGITAL WORLD JSC.</strong></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in 6pt 0.25in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-indent: -0.25in;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Địa chỉ:<strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>1174 Đường Láng, Phường Láng Thượng, Quận Đống Đa, Thành phố Hà Nội</strong></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Giấy CNĐKKD và Mã số doanh nghiệp số:<strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">&nbsp;0101217009 (số cũ: 0103018927) đăng ký thay đổi lần thứ 28&nbsp;do Sở Kế hoạch &amp; Đầu tư Thành phố Hà Nội cấp ngày 29/5/2015</strong></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Đại diện theo pháp luật của doanh nghiệp:<strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>Ông Trần Xuân Kiên - Chủ tịch HĐQT kiêm Tổng Giám đốc</strong></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: tahoma;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; font-weight: 700 !important; border: 0px none; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 18px; line-height: 27px; font-family: inherit;">1- Giới thiệu chung</span></strong></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: tahoma;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">Công ty TNHH Thương mại và Dịch vụ Trần Anh được thành lập theo Quyết định số 0102004703 ngày 11/3/2002 của Sở Kế hoạch và Đầu tư Thành phố Hà Nội. Công ty đã chính thức chuyển đổi từ mô hình công ty trách nhiệm hữu hạn sang mô hình công ty cổ phần với tên gọi mới là&nbsp;</span><a href="http://www.trananh.vn/" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;">Công 
            ty Cổ phần Thế giới số Trần Anh</span></a><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">&nbsp;kể từ ngày 08/8/2007 theo Giấy CNĐKKD số 0103018927 do Sở Kế hoạch và Đầu tư Thành phố Hà Nội cấp và đã chuyển sang số mới là 0101217009 kể từ ngày 29/5/2015.</span></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: tahoma;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">Ngày đầu thành lập, Trần Anh chỉ có 5 người làm việc trong một cửa hàng nhỏ với diện tích hơn 60m<sup style="box-sizing: border-box; margin: 0px; padding: 0px; position: relative; font-size: inherit; line-height: inherit; vertical-align: baseline; top: -0.5em; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-family: inherit;">2</sup>. Sau hơn 14 năm hoạt động, hiện nay quy mô Công ty đã tăng lên con số gần 3.000 nhân viên và<span class="Apple-converted-space">&nbsp;</span></span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;"><a href="http://www.trananh.vn/he-thong-sieu-thi-dien-may-tran-anh" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">2<span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; color: blue;">8</span><span class="Apple-converted-space">&nbsp;</span></a>trung 
            tâm bán lẻ</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>(trong đó có 5 trung tâm bán lẻ khai trương vào Quý III/2016).</span></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: tahoma;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">Là một trong những doanh nghiệp hàng đầu trong lĩnh vực bán lẻ điện máy, máy tính và điện thoại, kết thúc năm 2013, Trần Anh đã có 9 trung tâm bán lẻ phủ khắp địa bàn Hà Nội, đồng thời nhận được sự tin tưởng, ủng hộ của đông đảo Khách hàng Thủ đô. Khẳng định được vị thế tại Hà Nội, năm 2014 đánh dấu mốc son rực rỡ trên con đường chinh phục thị trường của Trần Anh với 7 trung tâm bán lẻ trải khắp các tỉnh, thành miền Bắc và miền Trung, đưa Trần Anh vào<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.trananh.vn/tin-tuc/tran-anh-dat-top-10-nha-ban-le-xuat-sac-nhat-viet-nam-n32188" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;">Top 
            10 nhà bán lẻ hàng đầu Việt Nam</span></a><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">. Kết thúc năm 2015, Trần Anh tiếp tục lộ trình phủ điểm thần tốc bằng việc mở mới thành công 6 trung tâm bán lẻ quy mô lớn, hiện đại, hướng tới chất lượng dịch vụ Nojima Nhật Bản, trở thành nhà bán lẻ điện máy dẫn đầu về số lượng điểm bán ở phía Bắc. Năm 2016, Trần Anh dự kiến mở mới 10 - 12 trung tâm mới. Đặc biệt kế hoạch khai trương đồng loạt 5 đại trung tâm diễn ra vào quý III/2016 đánh dấu sự chuyển mình của Trần Anh khi tự hào là thương hiệu điện máy miền Bắc đầu tiên có mặt tại thành phố Đà Nẵng với không chỉ một mà tới hai đại trung tâm điện máy với quy mô hoành tráng.<span class="Apple-converted-space">&nbsp;</span><br style="box-sizing: border-box; margin: 0px; padding: 0px;" />
            </span></span>
        </p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: inherit; font-family: tahoma;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;">Gắn liền với quá trình hoạt động và phát triển của Trần Anh là chính sách kinh doanh, dịch vụ hậu mãi tuyệt vời như:<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.trananh.vn/tin-tuc/tin-khuyen-mai-c919" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;">chính 
            sách kinh doanh</span></a><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>&quot;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">đưa sản phẩm chính hãng, giá tốt nhất đến tận tay người tiêu dùng</em>&quot;, phục vụ theo phương châm “<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">Khách hàng là Thượng đế</em>”,<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.trananh.vn/tin-tuc/chinh-sach/chinh-sach-bao-hanh-tran-anh-n516" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;">chính 
            sách bảo hành</span></a><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>&quot;<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">1 đổi 1</em>”, bán hàng trả góp lãi suất ưu đãi và<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.trananh.vn/tin-tuc/chinh-sach/chinh-sach-van-chuyen-mien-phi-toan-mien-bac-n1272" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit; color: blue;">dịch 
            vụ giao hàng</span></a><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 19.5px; font-family: inherit;"><span class="Apple-converted-space">&nbsp;</span>“<em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">vận chuyển, lắp đặt miễn phí trong vòng bán kính 100km</em>”… Đặc biệt, tại các trung tâm bán lẻ có diện tích lớn, Trần Anh còn tiến hành thiết kế, lắp đặt khu vui chơi trẻ em nhằm tăng thêm những trải nghiệm mua sắm mới và đa dạng hóa dịch vụ tiện ích cho Khách hàng, nhất là khách hộ gia đình. Qua đó, Trần Anh luôn duy trì được tốc độ tăng trưởng cao, toàn diện về mọi mặt một cách bền vững và đáng kinh ngạc so với các công ty kinh doanh cùng ngành. Thương 
            hiệu Trần Anh –<span class="Apple-converted-space">&nbsp;</span><em style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">Chuyên gia điện máy</em><span class="Apple-converted-space">&nbsp;</span>với biểu tượng ngôi sao 6 cánh tượng trưng cho sự bền vững đã trở nên quen thuộc, đồng thời tạo dựng được sự tin tưởng và hài lòng của Quý khách hàng.</span></span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Đến với hệ thống trung tâm bán lẻ Điện máy Trần Anh với không gian rộng rãi, thoáng mát và đội ngũ nhân viên tận tình, Khách hàng sẽ được thỏa sức trải nghiệm và chọn lựa hàng nghìn sản phẩm để trang bị cho tổ ấm của mình như Tivi, tủ lạnh, máy giặt, điều hòa; các sản phẩm điện gia dụng phục vụ nội trợ như nồi cơm điện, lò vi sóng, nồi, chảo; phục vụ sinh hoạt như quạt điện, bàn là, máy sấy tóc; các sản phẩm công nghệ phục vụ nhu cầu cá nhân như máy tính xách tay, máy tính bảng, điện thoại, máy ảnh, máy nghe nhạc… Tới Trần Anh, khách hàng cũng có thể mua sắm đầy đủ các máy móc phục vụ cho mục đích sử dụng của cơ quan, doanh nghiệp, hộ kinh doanh như máy tính, máy in, máy chiếu, máy photo… Tất cả các sản phẩm này đều thuộc các thương hiệu uy tín, có 
            nguồn gốc xuất xứ rõ ràng, giá cả cạnh tranh, chế độ bảo hành, bảo trì sản phẩm hết sức chu đáo.</span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Đặc biệt, Trần Anh luôn cập nhật các sản phẩm công nghệ mới và luôn có các chương trình<span class="Apple-converted-space">&nbsp;</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; text-decoration: underline; color: blue;"><a href="http://www.trananh.vn/khuyenmai.htm" style="box-sizing: border-box; margin: 0px; padding: 0px; background-color: transparent; color: rgb(51, 122, 183); text-decoration: none; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">khuyến 
            mãi</a></span><span class="Apple-converted-space">&nbsp;</span>đặc sắc: giá cả ưu đãi, quà tặng phong phú tới Khách hàng.</span></p>
        <p style="box-sizing: border-box; margin: 6pt 0in; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 18px; font-family: inherit; text-align: justify;">
            <span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 13px; line-height: 19.5px; font-family: tahoma;">Công ty Trần Anh có một đội ngũ nhân viên với trình độ chuyên môn cao (hơn 50% đã tốt nghiệp Đại học, Cao đẳng chuyên ngành Kinh tế, Kỹ thuật), đủ khả năng đáp ứng mọi yêu cầu dù là khắt khe nhất của Khách hàng. Không những thế, đội ngũ nhân viên của Trần Anh còn là những con người đầy lòng nhiệt huyết và luôn tận tình, niềm nở khi phục vụ Khách hàng. Tất cả các cán bộ, nhân viên trong Công ty Trần Anh đều thấu hiểu:</span></p>
        <br style="box-sizing: border-box; margin: 0px; padding: 0px;" />
        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">
        </p>
        <p class="MsoNormal" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: 20.4px; font-family: inherit;">
            <o:p style="box-sizing: border-box; margin: 0px; padding: 0px;"></o:p>
        </p>
        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">
        </p>
        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">
        </p>
        <p style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px none; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit;">
        </p>
    </div>
</asp:Content>